kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:latest
    extraPorts:
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
